### ISSUE TITLE
Not able to compile and buils this iperf , please help

### ISSUE THREAD

**Issue by bathepawan** [ouya/iperf#2]
I have clone this repo. and tried to build it but getting below error.

pbathe@pbathe-lt:~/work/ndk/android-ndk-r10e/iperf$ ../ndk-build NDK_APPLICATION_MK=Android.mk 
Android NDK: Could not find application project directory !  
Android NDK: Please define the NDK_PROJECT_PATH variable to point to it.  
/home/pbathe/work/ndk/android-ndk-r10e/build/core/build-local.mk:143: **\* Android NDK: Aborting    .  Stop.

Can somebody please help to understand what I am missing ?

**Comment by tgraupmann** [comment]
Android NDK: Please define the NDK_PROJECT_PATH variable to point to it.

This usually means your NDK environment variables aren't all setup.

ANDROID_NDK_HOME
ANDROID_NDK_PATH
ANDROID_NDK_ROOT
NDKROOT
NDK_ROOT

Like the error says make sure the NDK_PROJECT_PATH environment variable is pointing to the directory that you are building.

export NDK_PROJECT_PATH ~/work/ndk/android-ndk-r10e/iperf

Normally NDK_PROJECT_PATH is automatically setup when you run ndk-build...

I would try using JDK 7 or 8 with NDK R10...

**Comment by bathepawan** [comment]
thanks. able to compile it after defining all environment variables.
